name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2


profile: 'ecommerce_analytics'

vars:
  payment_methods:
    - credit_card
    - debit_card
    - upi
    


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


clean-targets:
  - "target"
  - "dbt_packages"


models:
  ecommerce_analytics:
    staging:
      +materialized: view


    marts:
      +materialized: table
