# Q2 - Write a custom iterator class that returns numbers from 1 to N.

# Constants
MAX_NUMBER = 9


class NumberSequenceIterator:
    """Custom iterator that returns numbers from 1 to N."""

    def __init__(self, limit: int) -> None:
        """Initialize the iterator with the upper limit."""
        self.limit = limit
        self.current_number = 1

    def __iter__(self) -> "NumberSequenceIterator":
        """Return the iterator object itself."""
        return self

    def __next__(self) -> int:
        """Return the next number in the sequence."""

        if self.current_number > self.limit:
            raise StopIteration

        next_number = self.current_number
        self.current_number += 1

        return next_number


def print_number_sequence(limit: int) -> None:
    """Print numbers generated by the custom iterator."""

    number_iterator = NumberSequenceIterator(limit)

    for number in number_iterator:
        print(number)


if __name__ == "__main__":
    print_number_sequence(MAX_NUMBER)