# Q3 - Write a generator function that yields square numbers up to N.

# Constants
MAX_NUMBER = 5


def generate_square_numbers(limit: int):
    """Yield square numbers from 1 to N."""

    for current_number in range(1, limit + 1):
        yield current_number ** 2


def print_square_numbers(limit: int) -> None:
    """Print square numbers generated by the generator."""

    square_generator = generate_square_numbers(limit)

    for square_number in square_generator:
        print(square_number)


if __name__ == "__main__":
    print_square_numbers(MAX_NUMBER)