# Q4 - Write a generator to produce Fibonacci numbers.

# Constants
FIBONACCI_SEQUENCE_LENGTH = 10


def generate_fibonacci_sequence(sequence_length: int):
    """Yield Fibonacci numbers up to the specified sequence length."""

    previous_number = 0
    current_number = 1

    for _ in range(sequence_length):
        yield previous_number

        next_number = previous_number + current_number
        previous_number = current_number
        current_number = next_number


def print_fibonacci_sequence(sequence_length: int) -> None:
    """Print Fibonacci numbers generated by the generator."""

    fibonacci_generator = generate_fibonacci_sequence(
        sequence_length
    )

    for fibonacci_number in fibonacci_generator:
        print(fibonacci_number)


if __name__ == "__main__":
    print_fibonacci_sequence(
        FIBONACCI_SEQUENCE_LENGTH
    )