# Q5 - Write a generator expression to generate even numbers from 1 to 50.

# Constants
MAX_NUMBER = 50


def generate_even_numbers(limit: int):
    """Generate even numbers using a generator expression."""

    return (
        current_number
        for current_number in range(1, limit + 1)
        if current_number % 2 == 0
    )


def print_even_numbers(limit: int) -> None:
    """Print even numbers generated by the generator expression."""

    even_number_generator = generate_even_numbers(
        limit
    )

    for even_number in even_number_generator:
        print(even_number)


if __name__ == "__main__":
    print_even_numbers(
        MAX_NUMBER
    )